/* tslint:disable */
/* eslint-disable */
/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  \'podman info\'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  \'podman pull quay.io/containers/podman\'  curl -XPOST --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman\'  \'podman list images\'  curl --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/libpod/images/json\' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  ListResponse,
  Volume,
  VolumeCreate,
  VolumesPruneReport,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    ListResponseFromJSON,
    ListResponseToJSON,
    VolumeFromJSON,
    VolumeToJSON,
    VolumeCreateFromJSON,
    VolumeCreateToJSON,
    VolumesPruneReportFromJSON,
    VolumesPruneReportToJSON,
} from '../models/index';

export interface VolumeCreateRequest {
    create?: VolumeCreate;
}

export interface VolumeDeleteRequest {
    name: string;
    force?: boolean;
}

export interface VolumeInspectRequest {
    name: string;
}

export interface VolumeListRequest {
    filters?: string;
}

export interface VolumePruneRequest {
    filters?: string;
}

/**
 * 
 */
export class VolumesCompatApi extends runtime.BaseAPI {

    /**
     * Create a volume
     */
    async volumeCreateRaw(requestParameters: VolumeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Volume>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/volumes/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VolumeCreateToJSON(requestParameters['create']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VolumeFromJSON(jsonValue));
    }

    /**
     * Create a volume
     */
    async volumeCreate(requestParameters: VolumeCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Volume> {
        const response = await this.volumeCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove volume
     */
    async volumeDeleteRaw(requestParameters: VolumeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling volumeDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/volumes/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove volume
     */
    async volumeDelete(requestParameters: VolumeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.volumeDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Inspect volume
     */
    async volumeInspectRaw(requestParameters: VolumeInspectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Volume>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling volumeInspect().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/volumes/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VolumeFromJSON(jsonValue));
    }

    /**
     * Inspect volume
     */
    async volumeInspect(requestParameters: VolumeInspectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Volume> {
        const response = await this.volumeInspectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of volume
     * List volumes
     */
    async volumeListRaw(requestParameters: VolumeListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['filters'] != null) {
            queryParameters['filters'] = requestParameters['filters'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/volumes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseFromJSON(jsonValue));
    }

    /**
     * Returns a list of volume
     * List volumes
     */
    async volumeList(requestParameters: VolumeListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponse> {
        const response = await this.volumeListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Prune volumes
     */
    async volumePruneRaw(requestParameters: VolumePruneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VolumesPruneReport>> {
        const queryParameters: any = {};

        if (requestParameters['filters'] != null) {
            queryParameters['filters'] = requestParameters['filters'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/volumes/prune`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VolumesPruneReportFromJSON(jsonValue));
    }

    /**
     * Prune volumes
     */
    async volumePrune(requestParameters: VolumePruneRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VolumesPruneReport> {
        const response = await this.volumePruneRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
