/* tslint:disable */
/* eslint-disable */
/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  \'podman info\'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  \'podman pull quay.io/containers/podman\'  curl -XPOST --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman\'  \'podman list images\'  curl --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/libpod/images/json\' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClusterVolumeSpec } from './ClusterVolumeSpec';
import {
    ClusterVolumeSpecFromJSON,
    ClusterVolumeSpecFromJSONTyped,
    ClusterVolumeSpecToJSON,
} from './ClusterVolumeSpec';
import type { Version } from './Version';
import {
    VersionFromJSON,
    VersionFromJSONTyped,
    VersionToJSON,
} from './Version';
import type { Info } from './Info';
import {
    InfoFromJSON,
    InfoFromJSONTyped,
    InfoToJSON,
} from './Info';
import type { PublishStatus } from './PublishStatus';
import {
    PublishStatusFromJSON,
    PublishStatusFromJSONTyped,
    PublishStatusToJSON,
} from './PublishStatus';

/**
 * ClusterVolume contains options and information specific to, and only present
 * on, Swarm CSI cluster volumes.
 * @export
 * @interface ClusterVolume
 */
export interface ClusterVolume {
    /**
     * 
     * @type {Date}
     * @memberof ClusterVolume
     */
    createdAt?: Date;
    /**
     * ID is the Swarm ID of the volume. Because cluster volumes are Swarm
     * objects, they have an ID, unlike non-cluster volumes, which only have a
     * Name. This ID can be used to refer to the cluster volume.
     * @type {string}
     * @memberof ClusterVolume
     */
    iD?: string;
    /**
     * 
     * @type {Info}
     * @memberof ClusterVolume
     */
    info?: Info;
    /**
     * PublishStatus contains the status of the volume as it pertains to its
     * publishing on Nodes.
     * @type {Array<PublishStatus>}
     * @memberof ClusterVolume
     */
    publishStatus?: Array<PublishStatus>;
    /**
     * 
     * @type {ClusterVolumeSpec}
     * @memberof ClusterVolume
     */
    spec?: ClusterVolumeSpec;
    /**
     * 
     * @type {Date}
     * @memberof ClusterVolume
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Version}
     * @memberof ClusterVolume
     */
    version?: Version;
}

/**
 * Check if a given object implements the ClusterVolume interface.
 */
export function instanceOfClusterVolume(value: object): value is ClusterVolume {
    return true;
}

export function ClusterVolumeFromJSON(json: any): ClusterVolume {
    return ClusterVolumeFromJSONTyped(json, false);
}

export function ClusterVolumeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterVolume {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['CreatedAt'] == null ? undefined : (new Date(json['CreatedAt'])),
        'iD': json['ID'] == null ? undefined : json['ID'],
        'info': json['Info'] == null ? undefined : InfoFromJSON(json['Info']),
        'publishStatus': json['PublishStatus'] == null ? undefined : ((json['PublishStatus'] as Array<any>).map(PublishStatusFromJSON)),
        'spec': json['Spec'] == null ? undefined : ClusterVolumeSpecFromJSON(json['Spec']),
        'updatedAt': json['UpdatedAt'] == null ? undefined : (new Date(json['UpdatedAt'])),
        'version': json['Version'] == null ? undefined : VersionFromJSON(json['Version']),
    };
}

export function ClusterVolumeToJSON(value?: ClusterVolume | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'CreatedAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'ID': value['iD'],
        'Info': InfoToJSON(value['info']),
        'PublishStatus': value['publishStatus'] == null ? undefined : ((value['publishStatus'] as Array<any>).map(PublishStatusToJSON)),
        'Spec': ClusterVolumeSpecToJSON(value['spec']),
        'UpdatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'Version': VersionToJSON(value['version']),
    };
}

