/* tslint:disable */
/* eslint-disable */
/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  \'podman info\'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  \'podman pull quay.io/containers/podman\'  curl -XPOST --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman\'  \'podman list images\'  curl --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/libpod/images/json\' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Secret } from './Secret';
import {
    SecretFromJSON,
    SecretFromJSONTyped,
    SecretToJSON,
} from './Secret';
import type { LinuxDeviceCgroup } from './LinuxDeviceCgroup';
import {
    LinuxDeviceCgroupFromJSON,
    LinuxDeviceCgroupFromJSONTyped,
    LinuxDeviceCgroupToJSON,
} from './LinuxDeviceCgroup';
import type { Mount } from './Mount';
import {
    MountFromJSON,
    MountFromJSONTyped,
    MountToJSON,
} from './Mount';
import type { NamedVolume } from './NamedVolume';
import {
    NamedVolumeFromJSON,
    NamedVolumeFromJSONTyped,
    NamedVolumeToJSON,
} from './NamedVolume';
import type { OverlayVolume } from './OverlayVolume';
import {
    OverlayVolumeFromJSON,
    OverlayVolumeFromJSONTyped,
    OverlayVolumeToJSON,
} from './OverlayVolume';
import type { LinuxDevice } from './LinuxDevice';
import {
    LinuxDeviceFromJSON,
    LinuxDeviceFromJSONTyped,
    LinuxDeviceToJSON,
} from './LinuxDevice';
import type { ImageVolume } from './ImageVolume';
import {
    ImageVolumeFromJSON,
    ImageVolumeFromJSONTyped,
    ImageVolumeToJSON,
} from './ImageVolume';
import type { Namespace } from './Namespace';
import {
    NamespaceFromJSON,
    NamespaceFromJSONTyped,
    NamespaceToJSON,
} from './Namespace';

/**
 * ContainerStorageConfig contains information on the storage configuration of a
 * container.
 * @export
 * @interface ContainerStorageConfig
 */
export interface ContainerStorageConfig {
    /**
     * ChrootDirs is an additional set of directories that need to be
     * treated as root directories. Standard bind mounts will be mounted
     * into paths relative to these directories.
     * Optional.
     * @type {Array<string>}
     * @memberof ContainerStorageConfig
     */
    chrootDirectories?: Array<string>;
    /**
     * Create the working directory if it doesn't exist.
     * If unset, it doesn't create it.
     * Optional.
     * @type {boolean}
     * @memberof ContainerStorageConfig
     */
    createWorkingDir?: boolean;
    /**
     * DeviceCgroupRule are device cgroup rules that allow containers
     * to use additional types of devices.
     * @type {Array<LinuxDeviceCgroup>}
     * @memberof ContainerStorageConfig
     */
    deviceCgroupRule?: Array<LinuxDeviceCgroup>;
    /**
     * Devices are devices that will be added to the container.
     * Optional.
     * @type {Array<LinuxDevice>}
     * @memberof ContainerStorageConfig
     */
    devices?: Array<LinuxDevice>;
    /**
     * DevicesFrom specifies that this container will mount the device(s) from other container(s).
     * Optional.
     * @type {Array<string>}
     * @memberof ContainerStorageConfig
     */
    devicesFrom?: Array<string>;
    /**
     * HostDeviceList is used to recreate the mounted device on inherited containers
     * @type {Array<LinuxDevice>}
     * @memberof ContainerStorageConfig
     */
    hostDeviceList?: Array<LinuxDevice>;
    /**
     * Image is the image the container will be based on. The image will be
     * used as the container's root filesystem, and its environment vars,
     * volumes, and other configuration will be applied to the container.
     * Conflicts with Rootfs.
     * At least one of Image or Rootfs must be specified.
     * @type {string}
     * @memberof ContainerStorageConfig
     */
    image?: string;
    /**
     * ImageArch is the user-specified image architecture.
     * Used to select a different variant from a manifest list.
     * Optional.
     * @type {string}
     * @memberof ContainerStorageConfig
     */
    imageArch?: string;
    /**
     * ImageOS is the user-specified OS of the image.
     * Used to select a different variant from a manifest list.
     * Optional.
     * @type {string}
     * @memberof ContainerStorageConfig
     */
    imageOs?: string;
    /**
     * ImageVariant is the user-specified image variant.
     * Used to select a different variant from a manifest list.
     * Optional.
     * @type {string}
     * @memberof ContainerStorageConfig
     */
    imageVariant?: string;
    /**
     * ImageVolumeMode indicates how image volumes will be created.
     * Supported modes are "ignore" (do not create), "tmpfs" (create as
     * tmpfs), and "anonymous" (create as anonymous volumes).
     * The default if unset is anonymous.
     * Optional.
     * @type {string}
     * @memberof ContainerStorageConfig
     */
    imageVolumeMode?: string;
    /**
     * Image volumes bind-mount a container-image mount into the container.
     * Optional.
     * @type {Array<ImageVolume>}
     * @memberof ContainerStorageConfig
     */
    imageVolumes?: Array<ImageVolume>;
    /**
     * Init specifies that an init binary will be mounted into the
     * container, and will be used as PID1.
     * Optional.
     * @type {boolean}
     * @memberof ContainerStorageConfig
     */
    init?: boolean;
    /**
     * InitPath specifies the path to the init binary that will be added if
     * Init is specified above. If not specified, the default set in the
     * Libpod config will be used. Ignored if Init above is not set.
     * Optional.
     * @type {string}
     * @memberof ContainerStorageConfig
     */
    initPath?: string;
    /**
     * 
     * @type {Namespace}
     * @memberof ContainerStorageConfig
     */
    ipcns?: Namespace;
    /**
     * Mounts are mounts that will be added to the container.
     * These will supersede Image Volumes and VolumesFrom volumes where
     * there are conflicts.
     * Optional.
     * @type {Array<Mount>}
     * @memberof ContainerStorageConfig
     */
    mounts?: Array<Mount>;
    /**
     * Overlay volumes are named volumes that will be added to the container.
     * Optional.
     * @type {Array<OverlayVolume>}
     * @memberof ContainerStorageConfig
     */
    overlayVolumes?: Array<OverlayVolume>;
    /**
     * RawImageName is the user-specified and unprocessed input referring
     * to a local or a remote image.
     * Optional, but strongly encouraged to be set if Image is set.
     * @type {string}
     * @memberof ContainerStorageConfig
     */
    rawImageName?: string;
    /**
     * Rootfs is the path to a directory that will be used as the
     * container's root filesystem. No modification will be made to the
     * directory, it will be directly mounted into the container as root.
     * Conflicts with Image.
     * At least one of Image or Rootfs must be specified.
     * @type {string}
     * @memberof ContainerStorageConfig
     */
    rootfs?: string;
    /**
     * RootfsMapping specifies if there are UID/GID mappings to apply to the rootfs.
     * Optional.
     * @type {string}
     * @memberof ContainerStorageConfig
     */
    rootfsMapping?: string;
    /**
     * RootfsOverlay tells if rootfs is actually an overlay on top of base path.
     * Optional.
     * @type {boolean}
     * @memberof ContainerStorageConfig
     */
    rootfsOverlay?: boolean;
    /**
     * RootfsPropagation is the rootfs propagation mode for the container.
     * If not set, the default of rslave will be used.
     * Optional.
     * @type {string}
     * @memberof ContainerStorageConfig
     */
    rootfsPropagation?: string;
    /**
     * Secrets are the secrets that will be added to the container
     * Optional.
     * @type {Array<Secret>}
     * @memberof ContainerStorageConfig
     */
    secrets?: Array<Secret>;
    /**
     * ShmSize is the size of the tmpfs to mount in at /dev/shm, in bytes.
     * Conflicts with ShmSize if IpcNS is not private.
     * Optional.
     * @type {number}
     * @memberof ContainerStorageConfig
     */
    shmSize?: number;
    /**
     * ShmSizeSystemd is the size of systemd-specific tmpfs mounts
     * specifically /run, /run/lock, /var/log/journal and /tmp.
     * Optional
     * @type {number}
     * @memberof ContainerStorageConfig
     */
    shmSizeSystemd?: number;
    /**
     * StorageOpts is the container's storage options
     * Optional.
     * @type {{ [key: string]: string; }}
     * @memberof ContainerStorageConfig
     */
    storageOpts?: { [key: string]: string; };
    /**
     * Volatile specifies whether the container storage can be optimized
     * at the cost of not syncing all the dirty files in memory.
     * Optional.
     * @type {boolean}
     * @memberof ContainerStorageConfig
     */
    _volatile?: boolean;
    /**
     * Volumes are named volumes that will be added to the container.
     * These will supersede Image Volumes and VolumesFrom volumes where
     * there are conflicts.
     * Optional.
     * @type {Array<NamedVolume>}
     * @memberof ContainerStorageConfig
     */
    volumes?: Array<NamedVolume>;
    /**
     * VolumesFrom is a set of containers whose volumes will be added to
     * this container. The name or ID of the container must be provided, and
     * may optionally be followed by a : and then one or more
     * comma-separated options. Valid options are 'ro', 'rw', and 'z'.
     * Options will be used for all volumes sourced from the container.
     * Optional.
     * @type {Array<string>}
     * @memberof ContainerStorageConfig
     */
    volumesFrom?: Array<string>;
    /**
     * WorkDir is the container's working directory.
     * If unset, the default, /, will be used.
     * Optional.
     * @type {string}
     * @memberof ContainerStorageConfig
     */
    workDir?: string;
}

/**
 * Check if a given object implements the ContainerStorageConfig interface.
 */
export function instanceOfContainerStorageConfig(value: object): value is ContainerStorageConfig {
    return true;
}

export function ContainerStorageConfigFromJSON(json: any): ContainerStorageConfig {
    return ContainerStorageConfigFromJSONTyped(json, false);
}

export function ContainerStorageConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerStorageConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'chrootDirectories': json['chroot_directories'] == null ? undefined : json['chroot_directories'],
        'createWorkingDir': json['create_working_dir'] == null ? undefined : json['create_working_dir'],
        'deviceCgroupRule': json['device_cgroup_rule'] == null ? undefined : ((json['device_cgroup_rule'] as Array<any>).map(LinuxDeviceCgroupFromJSON)),
        'devices': json['devices'] == null ? undefined : ((json['devices'] as Array<any>).map(LinuxDeviceFromJSON)),
        'devicesFrom': json['devices_from'] == null ? undefined : json['devices_from'],
        'hostDeviceList': json['host_device_list'] == null ? undefined : ((json['host_device_list'] as Array<any>).map(LinuxDeviceFromJSON)),
        'image': json['image'] == null ? undefined : json['image'],
        'imageArch': json['image_arch'] == null ? undefined : json['image_arch'],
        'imageOs': json['image_os'] == null ? undefined : json['image_os'],
        'imageVariant': json['image_variant'] == null ? undefined : json['image_variant'],
        'imageVolumeMode': json['image_volume_mode'] == null ? undefined : json['image_volume_mode'],
        'imageVolumes': json['image_volumes'] == null ? undefined : ((json['image_volumes'] as Array<any>).map(ImageVolumeFromJSON)),
        'init': json['init'] == null ? undefined : json['init'],
        'initPath': json['init_path'] == null ? undefined : json['init_path'],
        'ipcns': json['ipcns'] == null ? undefined : NamespaceFromJSON(json['ipcns']),
        'mounts': json['mounts'] == null ? undefined : ((json['mounts'] as Array<any>).map(MountFromJSON)),
        'overlayVolumes': json['overlay_volumes'] == null ? undefined : ((json['overlay_volumes'] as Array<any>).map(OverlayVolumeFromJSON)),
        'rawImageName': json['raw_image_name'] == null ? undefined : json['raw_image_name'],
        'rootfs': json['rootfs'] == null ? undefined : json['rootfs'],
        'rootfsMapping': json['rootfs_mapping'] == null ? undefined : json['rootfs_mapping'],
        'rootfsOverlay': json['rootfs_overlay'] == null ? undefined : json['rootfs_overlay'],
        'rootfsPropagation': json['rootfs_propagation'] == null ? undefined : json['rootfs_propagation'],
        'secrets': json['secrets'] == null ? undefined : ((json['secrets'] as Array<any>).map(SecretFromJSON)),
        'shmSize': json['shm_size'] == null ? undefined : json['shm_size'],
        'shmSizeSystemd': json['shm_size_systemd'] == null ? undefined : json['shm_size_systemd'],
        'storageOpts': json['storage_opts'] == null ? undefined : json['storage_opts'],
        '_volatile': json['volatile'] == null ? undefined : json['volatile'],
        'volumes': json['volumes'] == null ? undefined : ((json['volumes'] as Array<any>).map(NamedVolumeFromJSON)),
        'volumesFrom': json['volumes_from'] == null ? undefined : json['volumes_from'],
        'workDir': json['work_dir'] == null ? undefined : json['work_dir'],
    };
}

export function ContainerStorageConfigToJSON(value?: ContainerStorageConfig | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chroot_directories': value['chrootDirectories'],
        'create_working_dir': value['createWorkingDir'],
        'device_cgroup_rule': value['deviceCgroupRule'] == null ? undefined : ((value['deviceCgroupRule'] as Array<any>).map(LinuxDeviceCgroupToJSON)),
        'devices': value['devices'] == null ? undefined : ((value['devices'] as Array<any>).map(LinuxDeviceToJSON)),
        'devices_from': value['devicesFrom'],
        'host_device_list': value['hostDeviceList'] == null ? undefined : ((value['hostDeviceList'] as Array<any>).map(LinuxDeviceToJSON)),
        'image': value['image'],
        'image_arch': value['imageArch'],
        'image_os': value['imageOs'],
        'image_variant': value['imageVariant'],
        'image_volume_mode': value['imageVolumeMode'],
        'image_volumes': value['imageVolumes'] == null ? undefined : ((value['imageVolumes'] as Array<any>).map(ImageVolumeToJSON)),
        'init': value['init'],
        'init_path': value['initPath'],
        'ipcns': NamespaceToJSON(value['ipcns']),
        'mounts': value['mounts'] == null ? undefined : ((value['mounts'] as Array<any>).map(MountToJSON)),
        'overlay_volumes': value['overlayVolumes'] == null ? undefined : ((value['overlayVolumes'] as Array<any>).map(OverlayVolumeToJSON)),
        'raw_image_name': value['rawImageName'],
        'rootfs': value['rootfs'],
        'rootfs_mapping': value['rootfsMapping'],
        'rootfs_overlay': value['rootfsOverlay'],
        'rootfs_propagation': value['rootfsPropagation'],
        'secrets': value['secrets'] == null ? undefined : ((value['secrets'] as Array<any>).map(SecretToJSON)),
        'shm_size': value['shmSize'],
        'shm_size_systemd': value['shmSizeSystemd'],
        'storage_opts': value['storageOpts'],
        'volatile': value['_volatile'],
        'volumes': value['volumes'] == null ? undefined : ((value['volumes'] as Array<any>).map(NamedVolumeToJSON)),
        'volumes_from': value['volumesFrom'],
        'work_dir': value['workDir'],
    };
}

