/* tslint:disable */
/* eslint-disable */
/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  \'podman info\'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  \'podman pull quay.io/containers/podman\'  curl -XPOST --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman\'  \'podman list images\'  curl --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/libpod/images/json\' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PerNetworkOptions } from './PerNetworkOptions';
import {
    PerNetworkOptionsFromJSON,
    PerNetworkOptionsFromJSONTyped,
    PerNetworkOptionsToJSON,
} from './PerNetworkOptions';
import type { PortMapping } from './PortMapping';
import {
    PortMappingFromJSON,
    PortMappingFromJSONTyped,
    PortMappingToJSON,
} from './PortMapping';
import type { Namespace } from './Namespace';
import {
    NamespaceFromJSON,
    NamespaceFromJSONTyped,
    NamespaceToJSON,
} from './Namespace';

/**
 * ContainerNetworkConfig contains information on a container's network
 * configuration.
 * @export
 * @interface ContainerNetworkConfig
 */
export interface ContainerNetworkConfig {
    /**
     * Map of networks names or ids that the container should join.
     * You can request additional settings for each network, you can
     * set network aliases, static ips, static mac address  and the
     * network interface name for this container on the specific network.
     * If the map is empty and the bridge network mode is set the container
     * will be joined to the default network.
     * Optional.
     * @type {{ [key: string]: PerNetworkOptions; }}
     * @memberof ContainerNetworkConfig
     */
    networks?: { [key: string]: PerNetworkOptions; };
    /**
     * BaseHostsFile is the path to a hosts file, the entries from this file
     * are added to the containers hosts file. As special value "image" is
     * allowed which uses the /etc/hosts file from within the image and "none"
     * which uses no base file at all. If it is empty we should default
     * to the base_hosts_file configuration in containers.conf.
     * Optional.
     * @type {string}
     * @memberof ContainerNetworkConfig
     */
    baseHostsFile?: string;
    /**
     * CNINetworks is a list of CNI networks to join the container to.
     * If this list is empty, the default CNI network will be joined
     * instead. If at least one entry is present, we will not join the
     * default network (unless it is part of this list).
     * Only available if NetNS is set to bridge.
     * Optional.
     * Deprecated: as of podman 4.0 use "Networks" instead.
     * @type {Array<string>}
     * @memberof ContainerNetworkConfig
     */
    cniNetworks?: Array<string>;
    /**
     * DNSOptions is a set of DNS options that will be used in the
     * container's resolv.conf, replacing the host's DNS options which are
     * used by default.
     * Conflicts with UseImageResolvConf.
     * Optional.
     * @type {Array<string>}
     * @memberof ContainerNetworkConfig
     */
    dnsOption?: Array<string>;
    /**
     * DNSSearch is a set of DNS search domains that will be used in the
     * container's resolv.conf, replacing the host's DNS search domains
     * which are used by default.
     * Conflicts with UseImageResolvConf.
     * Optional.
     * @type {Array<string>}
     * @memberof ContainerNetworkConfig
     */
    dnsSearch?: Array<string>;
    /**
     * DNSServers is a set of DNS servers that will be used in the
     * container's resolv.conf, replacing the host's DNS Servers which are
     * used by default.
     * Conflicts with UseImageResolvConf.
     * Optional.
     * @type {Array<string>}
     * @memberof ContainerNetworkConfig
     */
    dnsServer?: Array<string>;
    /**
     * Expose is a number of ports that will be forwarded to the container
     * if PublishExposedPorts is set.
     * Expose is a map of uint16 (port number) to a string representing
     * protocol i.e map[uint16]string. Allowed protocols are "tcp", "udp", and "sctp", or some
     * combination of the three separated by commas.
     * If protocol is set to "" we will assume TCP.
     * Only available if NetNS is set to Bridge or Slirp, and
     * PublishExposedPorts is set.
     * Optional.
     * @type {object}
     * @memberof ContainerNetworkConfig
     */
    expose?: object;
    /**
     * HostAdd is a set of hosts which will be added to the container's
     * etc/hosts file.
     * Conflicts with UseImageHosts.
     * Optional.
     * @type {Array<string>}
     * @memberof ContainerNetworkConfig
     */
    hostadd?: Array<string>;
    /**
     * 
     * @type {Namespace}
     * @memberof ContainerNetworkConfig
     */
    netns?: Namespace;
    /**
     * NetworkOptions are additional options for each network
     * Optional.
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ContainerNetworkConfig
     */
    networkOptions?: { [key: string]: Array<string>; };
    /**
     * PortBindings is a set of ports to map into the container.
     * Only available if NetNS is set to bridge, slirp, or pasta.
     * Optional.
     * @type {Array<PortMapping>}
     * @memberof ContainerNetworkConfig
     */
    portmappings?: Array<PortMapping>;
    /**
     * PublishExposedPorts will publish ports specified in the image to
     * random unused ports (guaranteed to be above 1024) on the host.
     * This is based on ports set in Expose below, and any ports specified
     * by the Image (if one is given).
     * Only available if NetNS is set to Bridge or Slirp.
     * Optional.
     * @type {boolean}
     * @memberof ContainerNetworkConfig
     */
    publishImagePorts?: boolean;
    /**
     * UseImageHosts indicates that /etc/hosts should not be managed by
     * Podman, and instead sourced from the image.
     * Conflicts with HostAdd.
     * Optional.
     * @type {boolean}
     * @memberof ContainerNetworkConfig
     */
    useImageHosts?: boolean;
    /**
     * UseImageResolvConf indicates that resolv.conf should not be managed
     * by Podman, but instead sourced from the image.
     * Conflicts with DNSServer, DNSSearch, DNSOption.
     * Optional.
     * @type {boolean}
     * @memberof ContainerNetworkConfig
     */
    useImageResolveConf?: boolean;
}

/**
 * Check if a given object implements the ContainerNetworkConfig interface.
 */
export function instanceOfContainerNetworkConfig(value: object): value is ContainerNetworkConfig {
    return true;
}

export function ContainerNetworkConfigFromJSON(json: any): ContainerNetworkConfig {
    return ContainerNetworkConfigFromJSONTyped(json, false);
}

export function ContainerNetworkConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerNetworkConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'networks': json['Networks'] == null ? undefined : (mapValues(json['Networks'], PerNetworkOptionsFromJSON)),
        'baseHostsFile': json['base_hosts_file'] == null ? undefined : json['base_hosts_file'],
        'cniNetworks': json['cni_networks'] == null ? undefined : json['cni_networks'],
        'dnsOption': json['dns_option'] == null ? undefined : json['dns_option'],
        'dnsSearch': json['dns_search'] == null ? undefined : json['dns_search'],
        'dnsServer': json['dns_server'] == null ? undefined : json['dns_server'],
        'expose': json['expose'] == null ? undefined : json['expose'],
        'hostadd': json['hostadd'] == null ? undefined : json['hostadd'],
        'netns': json['netns'] == null ? undefined : NamespaceFromJSON(json['netns']),
        'networkOptions': json['network_options'] == null ? undefined : json['network_options'],
        'portmappings': json['portmappings'] == null ? undefined : ((json['portmappings'] as Array<any>).map(PortMappingFromJSON)),
        'publishImagePorts': json['publish_image_ports'] == null ? undefined : json['publish_image_ports'],
        'useImageHosts': json['use_image_hosts'] == null ? undefined : json['use_image_hosts'],
        'useImageResolveConf': json['use_image_resolve_conf'] == null ? undefined : json['use_image_resolve_conf'],
    };
}

export function ContainerNetworkConfigToJSON(value?: ContainerNetworkConfig | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'Networks': value['networks'] == null ? undefined : (mapValues(value['networks'], PerNetworkOptionsToJSON)),
        'base_hosts_file': value['baseHostsFile'],
        'cni_networks': value['cniNetworks'],
        'dns_option': value['dnsOption'],
        'dns_search': value['dnsSearch'],
        'dns_server': value['dnsServer'],
        'expose': value['expose'],
        'hostadd': value['hostadd'],
        'netns': NamespaceToJSON(value['netns']),
        'network_options': value['networkOptions'],
        'portmappings': value['portmappings'] == null ? undefined : ((value['portmappings'] as Array<any>).map(PortMappingToJSON)),
        'publish_image_ports': value['publishImagePorts'],
        'use_image_hosts': value['useImageHosts'],
        'use_image_resolve_conf': value['useImageResolveConf'],
    };
}

