/* tslint:disable */
/* eslint-disable */
/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  \'podman info\'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  \'podman pull quay.io/containers/podman\'  curl -XPOST --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman\'  \'podman list images\'  curl --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/libpod/images/json\' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EndpointIPAMConfig } from './EndpointIPAMConfig';
import {
    EndpointIPAMConfigFromJSON,
    EndpointIPAMConfigFromJSONTyped,
    EndpointIPAMConfigToJSON,
} from './EndpointIPAMConfig';

/**
 * EndpointSettings stores the network endpoint details
 * @export
 * @interface EndpointSettings
 */
export interface EndpointSettings {
    /**
     * 
     * @type {Array<string>}
     * @memberof EndpointSettings
     */
    aliases?: Array<string>;
    /**
     * DNSNames holds all the (non fully qualified) DNS names associated to this endpoint. First entry is used to
     * generate PTR records.
     * @type {Array<string>}
     * @memberof EndpointSettings
     */
    dNSNames?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof EndpointSettings
     */
    driverOpts?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof EndpointSettings
     */
    endpointID?: string;
    /**
     * 
     * @type {string}
     * @memberof EndpointSettings
     */
    gateway?: string;
    /**
     * 
     * @type {string}
     * @memberof EndpointSettings
     */
    globalIPv6Address?: string;
    /**
     * 
     * @type {number}
     * @memberof EndpointSettings
     */
    globalIPv6PrefixLen?: number;
    /**
     * 
     * @type {EndpointIPAMConfig}
     * @memberof EndpointSettings
     */
    iPAMConfig?: EndpointIPAMConfig;
    /**
     * 
     * @type {string}
     * @memberof EndpointSettings
     */
    iPAddress?: string;
    /**
     * 
     * @type {number}
     * @memberof EndpointSettings
     */
    iPPrefixLen?: number;
    /**
     * 
     * @type {string}
     * @memberof EndpointSettings
     */
    iPv6Gateway?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EndpointSettings
     */
    links?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EndpointSettings
     */
    macAddress?: string;
    /**
     * Operational data
     * @type {string}
     * @memberof EndpointSettings
     */
    networkID?: string;
}

/**
 * Check if a given object implements the EndpointSettings interface.
 */
export function instanceOfEndpointSettings(value: object): value is EndpointSettings {
    return true;
}

export function EndpointSettingsFromJSON(json: any): EndpointSettings {
    return EndpointSettingsFromJSONTyped(json, false);
}

export function EndpointSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EndpointSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'aliases': json['Aliases'] == null ? undefined : json['Aliases'],
        'dNSNames': json['DNSNames'] == null ? undefined : json['DNSNames'],
        'driverOpts': json['DriverOpts'] == null ? undefined : json['DriverOpts'],
        'endpointID': json['EndpointID'] == null ? undefined : json['EndpointID'],
        'gateway': json['Gateway'] == null ? undefined : json['Gateway'],
        'globalIPv6Address': json['GlobalIPv6Address'] == null ? undefined : json['GlobalIPv6Address'],
        'globalIPv6PrefixLen': json['GlobalIPv6PrefixLen'] == null ? undefined : json['GlobalIPv6PrefixLen'],
        'iPAMConfig': json['IPAMConfig'] == null ? undefined : EndpointIPAMConfigFromJSON(json['IPAMConfig']),
        'iPAddress': json['IPAddress'] == null ? undefined : json['IPAddress'],
        'iPPrefixLen': json['IPPrefixLen'] == null ? undefined : json['IPPrefixLen'],
        'iPv6Gateway': json['IPv6Gateway'] == null ? undefined : json['IPv6Gateway'],
        'links': json['Links'] == null ? undefined : json['Links'],
        'macAddress': json['MacAddress'] == null ? undefined : json['MacAddress'],
        'networkID': json['NetworkID'] == null ? undefined : json['NetworkID'],
    };
}

export function EndpointSettingsToJSON(value?: EndpointSettings | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'Aliases': value['aliases'],
        'DNSNames': value['dNSNames'],
        'DriverOpts': value['driverOpts'],
        'EndpointID': value['endpointID'],
        'Gateway': value['gateway'],
        'GlobalIPv6Address': value['globalIPv6Address'],
        'GlobalIPv6PrefixLen': value['globalIPv6PrefixLen'],
        'IPAMConfig': EndpointIPAMConfigToJSON(value['iPAMConfig']),
        'IPAddress': value['iPAddress'],
        'IPPrefixLen': value['iPPrefixLen'],
        'IPv6Gateway': value['iPv6Gateway'],
        'Links': value['links'],
        'MacAddress': value['macAddress'],
        'NetworkID': value['networkID'],
    };
}

