/* tslint:disable */
/* eslint-disable */
/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  \'podman info\'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  \'podman pull quay.io/containers/podman\'  curl -XPOST --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman\'  \'podman list images\'  curl --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/libpod/images/json\' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConmonInfo } from './ConmonInfo';
import {
    ConmonInfoFromJSON,
    ConmonInfoFromJSONTyped,
    ConmonInfoToJSON,
} from './ConmonInfo';
import type { IDMappings } from './IDMappings';
import {
    IDMappingsFromJSON,
    IDMappingsFromJSONTyped,
    IDMappingsToJSON,
} from './IDMappings';
import type { PastaInfo } from './PastaInfo';
import {
    PastaInfoFromJSON,
    PastaInfoFromJSONTyped,
    PastaInfoToJSON,
} from './PastaInfo';
import type { RemoteSocket } from './RemoteSocket';
import {
    RemoteSocketFromJSON,
    RemoteSocketFromJSONTyped,
    RemoteSocketToJSON,
} from './RemoteSocket';
import type { NetworkInfo } from './NetworkInfo';
import {
    NetworkInfoFromJSON,
    NetworkInfoFromJSONTyped,
    NetworkInfoToJSON,
} from './NetworkInfo';
import type { OCIRuntimeInfo } from './OCIRuntimeInfo';
import {
    OCIRuntimeInfoFromJSON,
    OCIRuntimeInfoFromJSONTyped,
    OCIRuntimeInfoToJSON,
} from './OCIRuntimeInfo';
import type { CPUUsage } from './CPUUsage';
import {
    CPUUsageFromJSON,
    CPUUsageFromJSONTyped,
    CPUUsageToJSON,
} from './CPUUsage';
import type { SecurityInfo } from './SecurityInfo';
import {
    SecurityInfoFromJSON,
    SecurityInfoFromJSONTyped,
    SecurityInfoToJSON,
} from './SecurityInfo';
import type { DistributionInfo } from './DistributionInfo';
import {
    DistributionInfoFromJSON,
    DistributionInfoFromJSONTyped,
    DistributionInfoToJSON,
} from './DistributionInfo';
import type { SlirpInfo } from './SlirpInfo';
import {
    SlirpInfoFromJSON,
    SlirpInfoFromJSONTyped,
    SlirpInfoToJSON,
} from './SlirpInfo';

/**
 * HostInfo describes the libpod host
 * @export
 * @interface HostInfo
 */
export interface HostInfo {
    /**
     * 
     * @type {string}
     * @memberof HostInfo
     */
    arch?: string;
    /**
     * 
     * @type {string}
     * @memberof HostInfo
     */
    buildahVersion?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof HostInfo
     */
    cgroupControllers?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof HostInfo
     */
    cgroupManager?: string;
    /**
     * 
     * @type {string}
     * @memberof HostInfo
     */
    cgroupVersion?: string;
    /**
     * 
     * @type {ConmonInfo}
     * @memberof HostInfo
     */
    conmon?: ConmonInfo;
    /**
     * 
     * @type {CPUUsage}
     * @memberof HostInfo
     */
    cpuUtilization?: CPUUsage;
    /**
     * 
     * @type {number}
     * @memberof HostInfo
     */
    cpus?: number;
    /**
     * 
     * @type {string}
     * @memberof HostInfo
     */
    databaseBackend?: string;
    /**
     * 
     * @type {DistributionInfo}
     * @memberof HostInfo
     */
    distribution?: DistributionInfo;
    /**
     * 
     * @type {string}
     * @memberof HostInfo
     */
    eventLogger?: string;
    /**
     * 
     * @type {number}
     * @memberof HostInfo
     */
    freeLocks?: number;
    /**
     * 
     * @type {string}
     * @memberof HostInfo
     */
    hostname?: string;
    /**
     * 
     * @type {IDMappings}
     * @memberof HostInfo
     */
    idMappings?: IDMappings;
    /**
     * 
     * @type {string}
     * @memberof HostInfo
     */
    kernel?: string;
    /**
     * 
     * @type {string}
     * @memberof HostInfo
     */
    linkmode?: string;
    /**
     * 
     * @type {string}
     * @memberof HostInfo
     */
    logDriver?: string;
    /**
     * 
     * @type {number}
     * @memberof HostInfo
     */
    memFree?: number;
    /**
     * 
     * @type {number}
     * @memberof HostInfo
     */
    memTotal?: number;
    /**
     * 
     * @type {string}
     * @memberof HostInfo
     */
    networkBackend?: string;
    /**
     * 
     * @type {NetworkInfo}
     * @memberof HostInfo
     */
    networkBackendInfo?: NetworkInfo;
    /**
     * 
     * @type {OCIRuntimeInfo}
     * @memberof HostInfo
     */
    ociRuntime?: OCIRuntimeInfo;
    /**
     * 
     * @type {string}
     * @memberof HostInfo
     */
    os?: string;
    /**
     * 
     * @type {PastaInfo}
     * @memberof HostInfo
     */
    pasta?: PastaInfo;
    /**
     * 
     * @type {RemoteSocket}
     * @memberof HostInfo
     */
    remoteSocket?: RemoteSocket;
    /**
     * RootlessNetworkCmd returns the default rootless network command (slirp4netns or pasta)
     * @type {string}
     * @memberof HostInfo
     */
    rootlessNetworkCmd?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof HostInfo
     */
    runtimeInfo?: { [key: string]: object; };
    /**
     * 
     * @type {SecurityInfo}
     * @memberof HostInfo
     */
    security?: SecurityInfo;
    /**
     * ServiceIsRemote is true when the podman/libpod service is remote to the client
     * @type {boolean}
     * @memberof HostInfo
     */
    serviceIsRemote?: boolean;
    /**
     * 
     * @type {SlirpInfo}
     * @memberof HostInfo
     */
    slirp4netns?: SlirpInfo;
    /**
     * 
     * @type {number}
     * @memberof HostInfo
     */
    swapFree?: number;
    /**
     * 
     * @type {number}
     * @memberof HostInfo
     */
    swapTotal?: number;
    /**
     * 
     * @type {string}
     * @memberof HostInfo
     */
    uptime?: string;
    /**
     * 
     * @type {string}
     * @memberof HostInfo
     */
    variant?: string;
}

/**
 * Check if a given object implements the HostInfo interface.
 */
export function instanceOfHostInfo(value: object): value is HostInfo {
    return true;
}

export function HostInfoFromJSON(json: any): HostInfo {
    return HostInfoFromJSONTyped(json, false);
}

export function HostInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HostInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'arch': json['arch'] == null ? undefined : json['arch'],
        'buildahVersion': json['buildahVersion'] == null ? undefined : json['buildahVersion'],
        'cgroupControllers': json['cgroupControllers'] == null ? undefined : json['cgroupControllers'],
        'cgroupManager': json['cgroupManager'] == null ? undefined : json['cgroupManager'],
        'cgroupVersion': json['cgroupVersion'] == null ? undefined : json['cgroupVersion'],
        'conmon': json['conmon'] == null ? undefined : ConmonInfoFromJSON(json['conmon']),
        'cpuUtilization': json['cpuUtilization'] == null ? undefined : CPUUsageFromJSON(json['cpuUtilization']),
        'cpus': json['cpus'] == null ? undefined : json['cpus'],
        'databaseBackend': json['databaseBackend'] == null ? undefined : json['databaseBackend'],
        'distribution': json['distribution'] == null ? undefined : DistributionInfoFromJSON(json['distribution']),
        'eventLogger': json['eventLogger'] == null ? undefined : json['eventLogger'],
        'freeLocks': json['freeLocks'] == null ? undefined : json['freeLocks'],
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'idMappings': json['idMappings'] == null ? undefined : IDMappingsFromJSON(json['idMappings']),
        'kernel': json['kernel'] == null ? undefined : json['kernel'],
        'linkmode': json['linkmode'] == null ? undefined : json['linkmode'],
        'logDriver': json['logDriver'] == null ? undefined : json['logDriver'],
        'memFree': json['memFree'] == null ? undefined : json['memFree'],
        'memTotal': json['memTotal'] == null ? undefined : json['memTotal'],
        'networkBackend': json['networkBackend'] == null ? undefined : json['networkBackend'],
        'networkBackendInfo': json['networkBackendInfo'] == null ? undefined : NetworkInfoFromJSON(json['networkBackendInfo']),
        'ociRuntime': json['ociRuntime'] == null ? undefined : OCIRuntimeInfoFromJSON(json['ociRuntime']),
        'os': json['os'] == null ? undefined : json['os'],
        'pasta': json['pasta'] == null ? undefined : PastaInfoFromJSON(json['pasta']),
        'remoteSocket': json['remoteSocket'] == null ? undefined : RemoteSocketFromJSON(json['remoteSocket']),
        'rootlessNetworkCmd': json['rootlessNetworkCmd'] == null ? undefined : json['rootlessNetworkCmd'],
        'runtimeInfo': json['runtimeInfo'] == null ? undefined : json['runtimeInfo'],
        'security': json['security'] == null ? undefined : SecurityInfoFromJSON(json['security']),
        'serviceIsRemote': json['serviceIsRemote'] == null ? undefined : json['serviceIsRemote'],
        'slirp4netns': json['slirp4netns'] == null ? undefined : SlirpInfoFromJSON(json['slirp4netns']),
        'swapFree': json['swapFree'] == null ? undefined : json['swapFree'],
        'swapTotal': json['swapTotal'] == null ? undefined : json['swapTotal'],
        'uptime': json['uptime'] == null ? undefined : json['uptime'],
        'variant': json['variant'] == null ? undefined : json['variant'],
    };
}

export function HostInfoToJSON(value?: HostInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'arch': value['arch'],
        'buildahVersion': value['buildahVersion'],
        'cgroupControllers': value['cgroupControllers'],
        'cgroupManager': value['cgroupManager'],
        'cgroupVersion': value['cgroupVersion'],
        'conmon': ConmonInfoToJSON(value['conmon']),
        'cpuUtilization': CPUUsageToJSON(value['cpuUtilization']),
        'cpus': value['cpus'],
        'databaseBackend': value['databaseBackend'],
        'distribution': DistributionInfoToJSON(value['distribution']),
        'eventLogger': value['eventLogger'],
        'freeLocks': value['freeLocks'],
        'hostname': value['hostname'],
        'idMappings': IDMappingsToJSON(value['idMappings']),
        'kernel': value['kernel'],
        'linkmode': value['linkmode'],
        'logDriver': value['logDriver'],
        'memFree': value['memFree'],
        'memTotal': value['memTotal'],
        'networkBackend': value['networkBackend'],
        'networkBackendInfo': NetworkInfoToJSON(value['networkBackendInfo']),
        'ociRuntime': OCIRuntimeInfoToJSON(value['ociRuntime']),
        'os': value['os'],
        'pasta': PastaInfoToJSON(value['pasta']),
        'remoteSocket': RemoteSocketToJSON(value['remoteSocket']),
        'rootlessNetworkCmd': value['rootlessNetworkCmd'],
        'runtimeInfo': value['runtimeInfo'],
        'security': SecurityInfoToJSON(value['security']),
        'serviceIsRemote': value['serviceIsRemote'],
        'slirp4netns': SlirpInfoToJSON(value['slirp4netns']),
        'swapFree': value['swapFree'],
        'swapTotal': value['swapTotal'],
        'uptime': value['uptime'],
        'variant': value['variant'],
    };
}

