/* tslint:disable */
/* eslint-disable */
/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  \'podman info\'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  \'podman pull quay.io/containers/podman\'  curl -XPOST --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman\'  \'podman list images\'  curl --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/libpod/images/json\' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LibpodImageSummary
 */
export interface LibpodImageSummary {
    /**
     * Podman extensions
     * @type {string}
     * @memberof LibpodImageSummary
     */
    arch?: string;
    /**
     * 
     * @type {number}
     * @memberof LibpodImageSummary
     */
    containers?: number;
    /**
     * 
     * @type {number}
     * @memberof LibpodImageSummary
     */
    created?: number;
    /**
     * 
     * @type {boolean}
     * @memberof LibpodImageSummary
     */
    dangling?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LibpodImageSummary
     */
    digest?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof LibpodImageSummary
     */
    history?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof LibpodImageSummary
     */
    id?: string;
    /**
     * IsManifestList is a ptr so we can distinguish between a true
     * json empty response and false.  the docker compat side needs to return
     * empty; where as the libpod side needs a value of true or false
     * @type {boolean}
     * @memberof LibpodImageSummary
     */
    isManifestList?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LibpodImageSummary
     */
    labels?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof LibpodImageSummary
     */
    names?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof LibpodImageSummary
     */
    os?: string;
    /**
     * 
     * @type {string}
     * @memberof LibpodImageSummary
     */
    parentId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LibpodImageSummary
     */
    readOnly?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof LibpodImageSummary
     */
    repoDigests?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LibpodImageSummary
     */
    repoTags?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof LibpodImageSummary
     */
    sharedSize?: number;
    /**
     * 
     * @type {number}
     * @memberof LibpodImageSummary
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof LibpodImageSummary
     */
    virtualSize?: number;
}

/**
 * Check if a given object implements the LibpodImageSummary interface.
 */
export function instanceOfLibpodImageSummary(value: object): value is LibpodImageSummary {
    return true;
}

export function LibpodImageSummaryFromJSON(json: any): LibpodImageSummary {
    return LibpodImageSummaryFromJSONTyped(json, false);
}

export function LibpodImageSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LibpodImageSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'arch': json['Arch'] == null ? undefined : json['Arch'],
        'containers': json['Containers'] == null ? undefined : json['Containers'],
        'created': json['Created'] == null ? undefined : json['Created'],
        'dangling': json['Dangling'] == null ? undefined : json['Dangling'],
        'digest': json['Digest'] == null ? undefined : json['Digest'],
        'history': json['History'] == null ? undefined : json['History'],
        'id': json['Id'] == null ? undefined : json['Id'],
        'isManifestList': json['IsManifestList'] == null ? undefined : json['IsManifestList'],
        'labels': json['Labels'] == null ? undefined : json['Labels'],
        'names': json['Names'] == null ? undefined : json['Names'],
        'os': json['Os'] == null ? undefined : json['Os'],
        'parentId': json['ParentId'] == null ? undefined : json['ParentId'],
        'readOnly': json['ReadOnly'] == null ? undefined : json['ReadOnly'],
        'repoDigests': json['RepoDigests'] == null ? undefined : json['RepoDigests'],
        'repoTags': json['RepoTags'] == null ? undefined : json['RepoTags'],
        'sharedSize': json['SharedSize'] == null ? undefined : json['SharedSize'],
        'size': json['Size'] == null ? undefined : json['Size'],
        'virtualSize': json['VirtualSize'] == null ? undefined : json['VirtualSize'],
    };
}

export function LibpodImageSummaryToJSON(value?: LibpodImageSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'Arch': value['arch'],
        'Containers': value['containers'],
        'Created': value['created'],
        'Dangling': value['dangling'],
        'Digest': value['digest'],
        'History': value['history'],
        'Id': value['id'],
        'IsManifestList': value['isManifestList'],
        'Labels': value['labels'],
        'Names': value['names'],
        'Os': value['os'],
        'ParentId': value['parentId'],
        'ReadOnly': value['readOnly'],
        'RepoDigests': value['repoDigests'],
        'RepoTags': value['repoTags'],
        'SharedSize': value['sharedSize'],
        'Size': value['size'],
        'VirtualSize': value['virtualSize'],
    };
}

