/* tslint:disable */
/* eslint-disable */
/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  \'podman info\'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  \'podman pull quay.io/containers/podman\'  curl -XPOST --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman\'  \'podman list images\'  curl --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/libpod/images/json\' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LinuxWeightDevice } from './LinuxWeightDevice';
import {
    LinuxWeightDeviceFromJSON,
    LinuxWeightDeviceFromJSONTyped,
    LinuxWeightDeviceToJSON,
} from './LinuxWeightDevice';
import type { LinuxThrottleDevice } from './LinuxThrottleDevice';
import {
    LinuxThrottleDeviceFromJSON,
    LinuxThrottleDeviceFromJSONTyped,
    LinuxThrottleDeviceToJSON,
} from './LinuxThrottleDevice';

/**
 * LinuxBlockIO for Linux cgroup 'blkio' resource management
 * @export
 * @interface LinuxBlockIO
 */
export interface LinuxBlockIO {
    /**
     * Specifies tasks' weight in the given cgroup while competing with the cgroup's child cgroups, CFQ scheduler only
     * @type {number}
     * @memberof LinuxBlockIO
     */
    leafWeight?: number;
    /**
     * IO read rate limit per cgroup per device, bytes per second
     * @type {Array<LinuxThrottleDevice>}
     * @memberof LinuxBlockIO
     */
    throttleReadBpsDevice?: Array<LinuxThrottleDevice>;
    /**
     * IO read rate limit per cgroup per device, IO per second
     * @type {Array<LinuxThrottleDevice>}
     * @memberof LinuxBlockIO
     */
    throttleReadIOPSDevice?: Array<LinuxThrottleDevice>;
    /**
     * IO write rate limit per cgroup per device, bytes per second
     * @type {Array<LinuxThrottleDevice>}
     * @memberof LinuxBlockIO
     */
    throttleWriteBpsDevice?: Array<LinuxThrottleDevice>;
    /**
     * IO write rate limit per cgroup per device, IO per second
     * @type {Array<LinuxThrottleDevice>}
     * @memberof LinuxBlockIO
     */
    throttleWriteIOPSDevice?: Array<LinuxThrottleDevice>;
    /**
     * Specifies per cgroup weight
     * @type {number}
     * @memberof LinuxBlockIO
     */
    weight?: number;
    /**
     * Weight per cgroup per device, can override BlkioWeight
     * @type {Array<LinuxWeightDevice>}
     * @memberof LinuxBlockIO
     */
    weightDevice?: Array<LinuxWeightDevice>;
}

/**
 * Check if a given object implements the LinuxBlockIO interface.
 */
export function instanceOfLinuxBlockIO(value: object): value is LinuxBlockIO {
    return true;
}

export function LinuxBlockIOFromJSON(json: any): LinuxBlockIO {
    return LinuxBlockIOFromJSONTyped(json, false);
}

export function LinuxBlockIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinuxBlockIO {
    if (json == null) {
        return json;
    }
    return {
        
        'leafWeight': json['leafWeight'] == null ? undefined : json['leafWeight'],
        'throttleReadBpsDevice': json['throttleReadBpsDevice'] == null ? undefined : ((json['throttleReadBpsDevice'] as Array<any>).map(LinuxThrottleDeviceFromJSON)),
        'throttleReadIOPSDevice': json['throttleReadIOPSDevice'] == null ? undefined : ((json['throttleReadIOPSDevice'] as Array<any>).map(LinuxThrottleDeviceFromJSON)),
        'throttleWriteBpsDevice': json['throttleWriteBpsDevice'] == null ? undefined : ((json['throttleWriteBpsDevice'] as Array<any>).map(LinuxThrottleDeviceFromJSON)),
        'throttleWriteIOPSDevice': json['throttleWriteIOPSDevice'] == null ? undefined : ((json['throttleWriteIOPSDevice'] as Array<any>).map(LinuxThrottleDeviceFromJSON)),
        'weight': json['weight'] == null ? undefined : json['weight'],
        'weightDevice': json['weightDevice'] == null ? undefined : ((json['weightDevice'] as Array<any>).map(LinuxWeightDeviceFromJSON)),
    };
}

export function LinuxBlockIOToJSON(value?: LinuxBlockIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'leafWeight': value['leafWeight'],
        'throttleReadBpsDevice': value['throttleReadBpsDevice'] == null ? undefined : ((value['throttleReadBpsDevice'] as Array<any>).map(LinuxThrottleDeviceToJSON)),
        'throttleReadIOPSDevice': value['throttleReadIOPSDevice'] == null ? undefined : ((value['throttleReadIOPSDevice'] as Array<any>).map(LinuxThrottleDeviceToJSON)),
        'throttleWriteBpsDevice': value['throttleWriteBpsDevice'] == null ? undefined : ((value['throttleWriteBpsDevice'] as Array<any>).map(LinuxThrottleDeviceToJSON)),
        'throttleWriteIOPSDevice': value['throttleWriteIOPSDevice'] == null ? undefined : ((value['throttleWriteIOPSDevice'] as Array<any>).map(LinuxThrottleDeviceToJSON)),
        'weight': value['weight'],
        'weightDevice': value['weightDevice'] == null ? undefined : ((value['weightDevice'] as Array<any>).map(LinuxWeightDeviceToJSON)),
    };
}

