/* tslint:disable */
/* eslint-disable */
/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  \'podman info\'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  \'podman pull quay.io/containers/podman\'  curl -XPOST --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman\'  \'podman list images\'  curl --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/libpod/images/json\' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * LogConfig describes the logging characteristics for a container
 * @export
 * @interface LogConfigLibpod
 */
export interface LogConfigLibpod {
    /**
     * LogDriver is the container's log driver.
     * Optional.
     * @type {string}
     * @memberof LogConfigLibpod
     */
    driver?: string;
    /**
     * A set of options to accompany the log driver.
     * Optional.
     * @type {{ [key: string]: string; }}
     * @memberof LogConfigLibpod
     */
    options?: { [key: string]: string; };
    /**
     * LogPath is the path the container's logs will be stored at.
     * Only available if LogDriver is set to "json-file" or "k8s-file".
     * Optional.
     * @type {string}
     * @memberof LogConfigLibpod
     */
    path?: string;
    /**
     * Size is the maximum size of the log file
     * Optional.
     * @type {number}
     * @memberof LogConfigLibpod
     */
    size?: number;
}

/**
 * Check if a given object implements the LogConfigLibpod interface.
 */
export function instanceOfLogConfigLibpod(value: object): value is LogConfigLibpod {
    return true;
}

export function LogConfigLibpodFromJSON(json: any): LogConfigLibpod {
    return LogConfigLibpodFromJSONTyped(json, false);
}

export function LogConfigLibpodFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogConfigLibpod {
    if (json == null) {
        return json;
    }
    return {
        
        'driver': json['driver'] == null ? undefined : json['driver'],
        'options': json['options'] == null ? undefined : json['options'],
        'path': json['path'] == null ? undefined : json['path'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function LogConfigLibpodToJSON(value?: LogConfigLibpod | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'driver': value['driver'],
        'options': value['options'],
        'path': value['path'],
        'size': value['size'],
    };
}

