/* tslint:disable */
/* eslint-disable */
/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  \'podman info\'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  \'podman pull quay.io/containers/podman\'  curl -XPOST --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman\'  \'podman list images\'  curl --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/libpod/images/json\' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceInfo } from './ServiceInfo';
import {
    ServiceInfoFromJSON,
    ServiceInfoFromJSONTyped,
    ServiceInfoToJSON,
} from './ServiceInfo';
import type { IPAM } from './IPAM';
import {
    IPAMFromJSON,
    IPAMFromJSONTyped,
    IPAMToJSON,
} from './IPAM';
import type { PeerInfo } from './PeerInfo';
import {
    PeerInfoFromJSON,
    PeerInfoFromJSONTyped,
    PeerInfoToJSON,
} from './PeerInfo';
import type { ConfigReference } from './ConfigReference';
import {
    ConfigReferenceFromJSON,
    ConfigReferenceFromJSONTyped,
    ConfigReferenceToJSON,
} from './ConfigReference';
import type { EndpointResource } from './EndpointResource';
import {
    EndpointResourceFromJSON,
    EndpointResourceFromJSONTyped,
    EndpointResourceToJSON,
} from './EndpointResource';

/**
 * NetworkResource is the body of the "get network" http response message
 * @export
 * @interface NetworkResource
 */
export interface NetworkResource {
    /**
     * 
     * @type {boolean}
     * @memberof NetworkResource
     */
    attachable?: boolean;
    /**
     * 
     * @type {ConfigReference}
     * @memberof NetworkResource
     */
    configFrom?: ConfigReference;
    /**
     * 
     * @type {boolean}
     * @memberof NetworkResource
     */
    configOnly?: boolean;
    /**
     * 
     * @type {{ [key: string]: EndpointResource; }}
     * @memberof NetworkResource
     */
    containers?: { [key: string]: EndpointResource; };
    /**
     * 
     * @type {Date}
     * @memberof NetworkResource
     */
    created?: Date;
    /**
     * 
     * @type {string}
     * @memberof NetworkResource
     */
    driver?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NetworkResource
     */
    enableIPv6?: boolean;
    /**
     * 
     * @type {IPAM}
     * @memberof NetworkResource
     */
    iPAM?: IPAM;
    /**
     * 
     * @type {string}
     * @memberof NetworkResource
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NetworkResource
     */
    ingress?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NetworkResource
     */
    internal?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof NetworkResource
     */
    labels?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof NetworkResource
     */
    name?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof NetworkResource
     */
    options?: { [key: string]: string; };
    /**
     * 
     * @type {Array<PeerInfo>}
     * @memberof NetworkResource
     */
    peers?: Array<PeerInfo>;
    /**
     * 
     * @type {string}
     * @memberof NetworkResource
     */
    scope?: string;
    /**
     * 
     * @type {{ [key: string]: ServiceInfo; }}
     * @memberof NetworkResource
     */
    services?: { [key: string]: ServiceInfo; };
}

/**
 * Check if a given object implements the NetworkResource interface.
 */
export function instanceOfNetworkResource(value: object): value is NetworkResource {
    return true;
}

export function NetworkResourceFromJSON(json: any): NetworkResource {
    return NetworkResourceFromJSONTyped(json, false);
}

export function NetworkResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkResource {
    if (json == null) {
        return json;
    }
    return {
        
        'attachable': json['Attachable'] == null ? undefined : json['Attachable'],
        'configFrom': json['ConfigFrom'] == null ? undefined : ConfigReferenceFromJSON(json['ConfigFrom']),
        'configOnly': json['ConfigOnly'] == null ? undefined : json['ConfigOnly'],
        'containers': json['Containers'] == null ? undefined : (mapValues(json['Containers'], EndpointResourceFromJSON)),
        'created': json['Created'] == null ? undefined : (new Date(json['Created'])),
        'driver': json['Driver'] == null ? undefined : json['Driver'],
        'enableIPv6': json['EnableIPv6'] == null ? undefined : json['EnableIPv6'],
        'iPAM': json['IPAM'] == null ? undefined : IPAMFromJSON(json['IPAM']),
        'id': json['Id'] == null ? undefined : json['Id'],
        'ingress': json['Ingress'] == null ? undefined : json['Ingress'],
        'internal': json['Internal'] == null ? undefined : json['Internal'],
        'labels': json['Labels'] == null ? undefined : json['Labels'],
        'name': json['Name'] == null ? undefined : json['Name'],
        'options': json['Options'] == null ? undefined : json['Options'],
        'peers': json['Peers'] == null ? undefined : ((json['Peers'] as Array<any>).map(PeerInfoFromJSON)),
        'scope': json['Scope'] == null ? undefined : json['Scope'],
        'services': json['Services'] == null ? undefined : (mapValues(json['Services'], ServiceInfoFromJSON)),
    };
}

export function NetworkResourceToJSON(value?: NetworkResource | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'Attachable': value['attachable'],
        'ConfigFrom': ConfigReferenceToJSON(value['configFrom']),
        'ConfigOnly': value['configOnly'],
        'Containers': value['containers'] == null ? undefined : (mapValues(value['containers'], EndpointResourceToJSON)),
        'Created': value['created'] == null ? undefined : ((value['created']).toISOString()),
        'Driver': value['driver'],
        'EnableIPv6': value['enableIPv6'],
        'IPAM': IPAMToJSON(value['iPAM']),
        'Id': value['id'],
        'Ingress': value['ingress'],
        'Internal': value['internal'],
        'Labels': value['labels'],
        'Name': value['name'],
        'Options': value['options'],
        'Peers': value['peers'] == null ? undefined : ((value['peers'] as Array<any>).map(PeerInfoToJSON)),
        'Scope': value['scope'],
        'Services': value['services'] == null ? undefined : (mapValues(value['services'], ServiceInfoToJSON)),
    };
}

