/* tslint:disable */
/* eslint-disable */
/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  \'podman info\'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  \'podman pull quay.io/containers/podman\'  curl -XPOST --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman\'  \'podman list images\'  curl --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/libpod/images/json\' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayKubePod
 */
export interface PlayKubePod {
    /**
     * ContainerErrors - any errors that occurred while starting containers
     * in the pod.
     * @type {Array<string>}
     * @memberof PlayKubePod
     */
    containerErrors?: Array<string>;
    /**
     * Containers - the IDs of the containers running in the created pod.
     * @type {Array<string>}
     * @memberof PlayKubePod
     */
    containers?: Array<string>;
    /**
     * ID - ID of the pod created as a result of play kube.
     * @type {string}
     * @memberof PlayKubePod
     */
    iD?: string;
    /**
     * InitContainers - the IDs of the init containers to be run in the created pod.
     * @type {Array<string>}
     * @memberof PlayKubePod
     */
    initContainers?: Array<string>;
    /**
     * Logs - non-fatal errors and log messages while processing.
     * @type {Array<string>}
     * @memberof PlayKubePod
     */
    logs?: Array<string>;
}

/**
 * Check if a given object implements the PlayKubePod interface.
 */
export function instanceOfPlayKubePod(value: object): value is PlayKubePod {
    return true;
}

export function PlayKubePodFromJSON(json: any): PlayKubePod {
    return PlayKubePodFromJSONTyped(json, false);
}

export function PlayKubePodFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayKubePod {
    if (json == null) {
        return json;
    }
    return {
        
        'containerErrors': json['ContainerErrors'] == null ? undefined : json['ContainerErrors'],
        'containers': json['Containers'] == null ? undefined : json['Containers'],
        'iD': json['ID'] == null ? undefined : json['ID'],
        'initContainers': json['InitContainers'] == null ? undefined : json['InitContainers'],
        'logs': json['Logs'] == null ? undefined : json['Logs'],
    };
}

export function PlayKubePodToJSON(value?: PlayKubePod | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ContainerErrors': value['containerErrors'],
        'Containers': value['containers'],
        'ID': value['iD'],
        'InitContainers': value['initContainers'],
        'Logs': value['logs'],
    };
}

