/* tslint:disable */
/* eslint-disable */
/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  \'podman info\'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  \'podman pull quay.io/containers/podman\'  curl -XPOST --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman\'  \'podman list images\'  curl --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/libpod/images/json\' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetOptions } from './NetOptions';
import {
    NetOptionsFromJSON,
    NetOptionsFromJSONTyped,
    NetOptionsToJSON,
} from './NetOptions';

/**
 * The JSON tags below are made to match the respective field in ContainerCreateOptions for the purpose of mapping.
 * @export
 * @interface PodCreateOptions
 */
export interface PodCreateOptions {
    /**
     * 
     * @type {string}
     * @memberof PodCreateOptions
     */
    cgroupParent?: string;
    /**
     * 
     * @type {string}
     * @memberof PodCreateOptions
     */
    containerCommand?: string;
    /**
     * 
     * @type {string}
     * @memberof PodCreateOptions
     */
    containerConmonPidfile?: string;
    /**
     * 
     * @type {string}
     * @memberof PodCreateOptions
     */
    containerName?: string;
    /**
     * 
     * @type {number}
     * @memberof PodCreateOptions
     */
    cpus?: number;
    /**
     * 
     * @type {string}
     * @memberof PodCreateOptions
     */
    cpusetCpus?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PodCreateOptions
     */
    createCommand?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PodCreateOptions
     */
    deviceReadBps?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PodCreateOptions
     */
    devices?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PodCreateOptions
     */
    exitPolicy?: string;
    /**
     * 
     * @type {string}
     * @memberof PodCreateOptions
     */
    hostname?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PodCreateOptions
     */
    infra?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PodCreateOptions
     */
    infraImage?: string;
    /**
     * 
     * @type {string}
     * @memberof PodCreateOptions
     */
    ipc?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PodCreateOptions
     */
    labels?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof PodCreateOptions
     */
    name?: string;
    /**
     * 
     * @type {NetOptions}
     * @memberof PodCreateOptions
     */
    net?: NetOptions;
    /**
     * 
     * @type {string}
     * @memberof PodCreateOptions
     */
    pid?: string;
    /**
     * 
     * @type {string}
     * @memberof PodCreateOptions
     */
    restart?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PodCreateOptions
     */
    securityOpt?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PodCreateOptions
     */
    share?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof PodCreateOptions
     */
    shareParent?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof PodCreateOptions
     */
    sysctl?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PodCreateOptions
     */
    uts?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PodCreateOptions
     */
    volume?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PodCreateOptions
     */
    volumesFrom?: Array<string>;
}

/**
 * Check if a given object implements the PodCreateOptions interface.
 */
export function instanceOfPodCreateOptions(value: object): value is PodCreateOptions {
    return true;
}

export function PodCreateOptionsFromJSON(json: any): PodCreateOptions {
    return PodCreateOptionsFromJSONTyped(json, false);
}

export function PodCreateOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PodCreateOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'cgroupParent': json['cgroup_parent'] == null ? undefined : json['cgroup_parent'],
        'containerCommand': json['container_command'] == null ? undefined : json['container_command'],
        'containerConmonPidfile': json['container_conmon_pidfile'] == null ? undefined : json['container_conmon_pidfile'],
        'containerName': json['container_name'] == null ? undefined : json['container_name'],
        'cpus': json['cpus'] == null ? undefined : json['cpus'],
        'cpusetCpus': json['cpuset_cpus'] == null ? undefined : json['cpuset_cpus'],
        'createCommand': json['create_command'] == null ? undefined : json['create_command'],
        'deviceReadBps': json['device_read_bps'] == null ? undefined : json['device_read_bps'],
        'devices': json['devices'] == null ? undefined : json['devices'],
        'exitPolicy': json['exit_policy'] == null ? undefined : json['exit_policy'],
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'infra': json['infra'] == null ? undefined : json['infra'],
        'infraImage': json['infra_image'] == null ? undefined : json['infra_image'],
        'ipc': json['ipc'] == null ? undefined : json['ipc'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'name': json['name'] == null ? undefined : json['name'],
        'net': json['net'] == null ? undefined : NetOptionsFromJSON(json['net']),
        'pid': json['pid'] == null ? undefined : json['pid'],
        'restart': json['restart'] == null ? undefined : json['restart'],
        'securityOpt': json['security_opt'] == null ? undefined : json['security_opt'],
        'share': json['share'] == null ? undefined : json['share'],
        'shareParent': json['share_parent'] == null ? undefined : json['share_parent'],
        'sysctl': json['sysctl'] == null ? undefined : json['sysctl'],
        'uts': json['uts'] == null ? undefined : json['uts'],
        'volume': json['volume'] == null ? undefined : json['volume'],
        'volumesFrom': json['volumes_from'] == null ? undefined : json['volumes_from'],
    };
}

export function PodCreateOptionsToJSON(value?: PodCreateOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cgroup_parent': value['cgroupParent'],
        'container_command': value['containerCommand'],
        'container_conmon_pidfile': value['containerConmonPidfile'],
        'container_name': value['containerName'],
        'cpus': value['cpus'],
        'cpuset_cpus': value['cpusetCpus'],
        'create_command': value['createCommand'],
        'device_read_bps': value['deviceReadBps'],
        'devices': value['devices'],
        'exit_policy': value['exitPolicy'],
        'hostname': value['hostname'],
        'infra': value['infra'],
        'infra_image': value['infraImage'],
        'ipc': value['ipc'],
        'labels': value['labels'],
        'name': value['name'],
        'net': NetOptionsToJSON(value['net']),
        'pid': value['pid'],
        'restart': value['restart'],
        'security_opt': value['securityOpt'],
        'share': value['share'],
        'share_parent': value['shareParent'],
        'sysctl': value['sysctl'],
        'uts': value['uts'],
        'volume': value['volume'],
        'volumes_from': value['volumesFrom'],
    };
}

