/* tslint:disable */
/* eslint-disable */
/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  \'podman info\'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  \'podman pull quay.io/containers/podman\'  curl -XPOST --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman\'  \'podman list images\'  curl --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/libpod/images/json\' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PublishStatus represents the status of the volume as published to an
 * individual node
 * @export
 * @interface PublishStatus
 */
export interface PublishStatus {
    /**
     * NodeID is the ID of the swarm node this Volume is published to.
     * @type {string}
     * @memberof PublishStatus
     */
    nodeID?: string;
    /**
     * PublishContext is the PublishContext returned by the CSI plugin when
     * a volume is published.
     * @type {{ [key: string]: string; }}
     * @memberof PublishStatus
     */
    publishContext?: { [key: string]: string; };
    /**
     * PublishState represents the state of a Volume as it pertains to its
     * use on a particular Node.
     * @type {string}
     * @memberof PublishStatus
     */
    state?: string;
}

/**
 * Check if a given object implements the PublishStatus interface.
 */
export function instanceOfPublishStatus(value: object): value is PublishStatus {
    return true;
}

export function PublishStatusFromJSON(json: any): PublishStatus {
    return PublishStatusFromJSONTyped(json, false);
}

export function PublishStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'nodeID': json['NodeID'] == null ? undefined : json['NodeID'],
        'publishContext': json['PublishContext'] == null ? undefined : json['PublishContext'],
        'state': json['State'] == null ? undefined : json['State'],
    };
}

export function PublishStatusToJSON(value?: PublishStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'NodeID': value['nodeID'],
        'PublishContext': value['publishContext'],
        'State': value['state'],
    };
}

