/* tslint:disable */
/* eslint-disable */
/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  \'podman info\'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  \'podman pull quay.io/containers/podman\'  curl -XPOST --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman\'  \'podman list images\'  curl --unix-socket /run/podman/podman.sock -v \'http://d/v5.0.0/libpod/images/json\' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemDfImageReport } from './SystemDfImageReport';
import {
    SystemDfImageReportFromJSON,
    SystemDfImageReportFromJSONTyped,
    SystemDfImageReportToJSON,
} from './SystemDfImageReport';
import type { SystemDfVolumeReport } from './SystemDfVolumeReport';
import {
    SystemDfVolumeReportFromJSON,
    SystemDfVolumeReportFromJSONTyped,
    SystemDfVolumeReportToJSON,
} from './SystemDfVolumeReport';
import type { SystemDfContainerReport } from './SystemDfContainerReport';
import {
    SystemDfContainerReportFromJSON,
    SystemDfContainerReportFromJSONTyped,
    SystemDfContainerReportToJSON,
} from './SystemDfContainerReport';

/**
 * SystemDfReport describes the response for df information
 * @export
 * @interface SystemDfReport
 */
export interface SystemDfReport {
    /**
     * 
     * @type {Array<SystemDfContainerReport>}
     * @memberof SystemDfReport
     */
    containers?: Array<SystemDfContainerReport>;
    /**
     * 
     * @type {Array<SystemDfImageReport>}
     * @memberof SystemDfReport
     */
    images?: Array<SystemDfImageReport>;
    /**
     * 
     * @type {number}
     * @memberof SystemDfReport
     */
    imagesSize?: number;
    /**
     * 
     * @type {Array<SystemDfVolumeReport>}
     * @memberof SystemDfReport
     */
    volumes?: Array<SystemDfVolumeReport>;
}

/**
 * Check if a given object implements the SystemDfReport interface.
 */
export function instanceOfSystemDfReport(value: object): value is SystemDfReport {
    return true;
}

export function SystemDfReportFromJSON(json: any): SystemDfReport {
    return SystemDfReportFromJSONTyped(json, false);
}

export function SystemDfReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemDfReport {
    if (json == null) {
        return json;
    }
    return {
        
        'containers': json['Containers'] == null ? undefined : ((json['Containers'] as Array<any>).map(SystemDfContainerReportFromJSON)),
        'images': json['Images'] == null ? undefined : ((json['Images'] as Array<any>).map(SystemDfImageReportFromJSON)),
        'imagesSize': json['ImagesSize'] == null ? undefined : json['ImagesSize'],
        'volumes': json['Volumes'] == null ? undefined : ((json['Volumes'] as Array<any>).map(SystemDfVolumeReportFromJSON)),
    };
}

export function SystemDfReportToJSON(value?: SystemDfReport | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'Containers': value['containers'] == null ? undefined : ((value['containers'] as Array<any>).map(SystemDfContainerReportToJSON)),
        'Images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(SystemDfImageReportToJSON)),
        'ImagesSize': value['imagesSize'],
        'Volumes': value['volumes'] == null ? undefined : ((value['volumes'] as Array<any>).map(SystemDfVolumeReportToJSON)),
    };
}

